# Generated by Django 4.1.3 on 2022-11-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('rarity', models.CharField(choices=[('r-1', 'More than 5,000 in existence'), ('r-2', 'Between 2,000 and 5,000 in existence'), ('r-3', 'Between 500 and 2,000 in existence'), ('r-4', 'Between 200 and 500 in existence'), ('r-5', 'Between 75 and 200 in existence'), ('r-6', 'Between 20 and 75 in existence'), ('r-7', 'Between 10 and 20 in existence'), ('r-8', 'Between 5 and 10 in existence'), ('r-9', 'Between 2 and 4 in existence'), ('r-10', 'Unique, only one known example')], default='r-1', max_length=4)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
