# Generated by Django 4.1.3 on 2022-11-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_materials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
